security:
    encoders:
        Cms\CoreBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity:
              class:    CmsCoreBundle:User
              property: email

    firewalls:
        core_login:
            pattern:  ^/admin/auth/(login|forget-password)$
            security: false

        core_secured:
            pattern:  ^/admin
            form_login:
                check_path: core_auth_check
                login_path: core_auth_login
                username_parameter: email
                password_parameter: password
            logout:
                path:   core_auth_logout
                target: core_auth_login