security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
        # Include the following line to also secure the /admin path itself
        # - { path: ^/admin$, roles: ROLE_ADMIN }

    firewalls:
        core_allowed:
            pattern:  ^/admin/(login|forget-password)
            security: false
        core_secure:
            pattern:  ^/admin
            form_login:
                check_path:          core_login_auth
                login_path:          core_login
                default_target_path: core_dashboard
                username_parameter:  email
                password_parameter:  password
            logout:
                path:   core_logout
                target: core_login